### ISSUE TITLE
Invalid URL when trying to download CHELSA-TraCE21k monthly data

### ISSUE THREAD

**Issue by joeroe** [EvolEcolGroup/pastclim#66]
With the latest dev version of pastclim (5d36a575d3c235d5a1a2f8dd25d3bc44302fb253), trying to download monthly CHELSA-TraCE21k causes an error:
                        
``` r
library(pastclim)
#> Loading required package: terra
#> terra 1.8.26
download_dataset("CHELSA_trace21k_1.0_0.5m_vsi", annual = FALSE, monthly = TRUE)
#> Error in eval(parse(text = file_details$download_function))(dataset = dataset, : invalid URL for variable temperature_min_01; either the server can not be reached at the moment, or the path has changed
```

<sup>Created on 2025-02-19 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details>
<summary>Session info</summary>

```r
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.12.0 
LAPACK: /usr/lib/liblapack.so.3.12.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Copenhagen
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] patchwork_1.3.0     cowplot_1.1.3       tidyr_1.3.1         dplyr_1.1.4         ggplot2_3.5.1      
 [6] era_0.5.0           pastclim_2.1.0.9002 terra_1.8-26        here_1.0.1          nvimcom_0.9-167    
[11] colorout_1.3-2     

loaded via a namespace (and not attached):
 [1] utf8_1.2.4         generics_0.1.3     class_7.3-22       tcltk_4.4.2        xml2_1.3.6         KernSmooth_2.23-24
 [7] digest_0.6.37      magrittr_2.0.3     evaluate_1.0.3     grid_4.4.2         fastmap_1.2.0      rprojroot_2.0.4   
[13] processx_3.8.5     e1071_1.7-16       DBI_1.2.3          ps_1.9.0           httr_1.4.7         purrr_1.0.4       
[19] scales_1.3.0       codetools_0.2-20   textshaping_1.0.0  cli_3.6.4          rlang_1.1.5        units_0.8-5       
[25] munsell_0.5.1      reprex_2.1.1       yaml_2.3.10        withr_3.0.2        tools_4.4.2        colorspace_2.1-1  
[31] curl_6.2.0         vctrs_0.6.5        R6_2.6.1           proxy_0.4-27       lifecycle_1.0.4    classInt_0.4-11   
[37] fs_1.6.5           ragg_1.3.3         clipr_0.8.0        callr_3.7.6        pkgconfig_2.0.3    pillar_1.10.1     
[43] gtable_0.3.6       glue_1.8.0         Rcpp_1.0.14        sf_1.0-19          systemfonts_1.2.1  xfun_0.50         
[49] tibble_3.2.1       tidyselect_1.2.1   rstudioapi_0.17.1  knitr_1.49         farver_2.1.2       htmltools_0.5.8.1 
[55] rmarkdown_2.29     labeling_0.4.3     compiler_4.4.2    

```
</details>

**Comment by dramanica** [comment]
@joeroe Thanks for reporting this issue. I have just uploaded a fix; could you try installing with `devtools` from the `dev` branch of GitHub (it should be version 2.1.0.9003 and see whether it fixes your problem?

**Comment by ltyrone** [comment]
Similar issue, except debug mode is triggered when using the dev version. Reprex:
```r
install.packages("pastclim", repos = c("https://evolecolgroup.r-universe.dev"))

library(pastclim) # pastclim_2.1.0.9004  

set_data_path("C:/path/to/folder")

help("CHELSA_trace21k_1.0_0.5m_vsi")
# Internal Server Error (in RStudio Help panel)

download_dataset(dataset = "CHELSA_trace21k_1.0_0.5m_vsi")
# Called from: eval(parse(text = file_details$download_function))(dataset = dataset, 
#     bio_var = this_var, filename = file.path(get_data_path(), 
#         file_details$file_name))
# Browse[1]> 
```
Line 29 in the eval is highlighted. 

This works fine:
```r
download_dataset("Beyer2020")
# [100%] Downloaded 295 bytes...
# [1%] Downloaded 4997896 bytes...
```

**Comment by dramanica** [comment]
Sorry, I had left a `browser()` statement whilst fixing the code. It should now be removed in version 2.1.0.9005.

**Comment by ltyrone** [comment]
> Sorry, I had left a `browser()` statement whilst fixing the code. It should now be removed in version 2.1.0.9005.

Working again, most appreciated. One further question:
```r
download_dataset(dataset = "CHELSA_trace21k_1.0_0.5m_vsi")
# This operation will take little while, as it needs to collate
#  information from many files...
```
is currently working at ~8kb/s. I do have a poor internet connection but it's usually faster than this for similar processes. Is this normal for just the collation process and things will speed up once the collation is complete? Or is this just a result of poor internet?

Thanks again

**Comment by dramanica** [comment]
Hi @ltyrone, glad to hear it is fixed! Unfortunately the CHELSA server can be pretty slow at times, so the speed really depends on whether you ping it on a good day or not...

**Comment by joeroe** [comment]
Thanks for the quick fix @dramanica. Unfortunately I'm still getting the same error with the monthly data in v2.2.0 and v2.2.0.9000, though now it's tripping up on `temperature_min_07`:

```r
library(pastclim)
#> Loading required package: terra
#> terra 1.8.26
download_dataset("CHELSA_trace21k_1.0_0.5m_vsi", annual = FALSE, monthly = TRUE)
#> Error in eval(parse(text = file_details$download_function))(dataset = dataset, : invalid URL for variable temperature_min_07; either the server can not be reached at the moment, or the path has changed
```

<sup>Created on 2025-02-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

<details>
<summary>Session info</summary>

```r
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: Arch Linux

Matrix products: default
BLAS:   /usr/lib/libblas.so.3.12.0 
LAPACK: /usr/lib/liblapack.so.3.12.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8     LC_MONETARY=en_GB.UTF-8   
 [6] LC_MESSAGES=en_GB.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Copenhagen
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] nvimcom_0.9-167 colorout_1.3-2 

loaded via a namespace (and not attached):
 [1] digest_0.6.37     R6_2.6.1          fastmap_1.2.0     xfun_0.50         magrittr_2.0.3    glue_1.8.0        tibble_3.2.1      knitr_1.49       
 [9] pkgconfig_2.0.3   htmltools_0.5.8.1 rmarkdown_2.29    lifecycle_1.0.4   ps_1.9.0          cli_3.6.4         processx_3.8.5    callr_3.7.6      
[17] vctrs_0.6.5       reprex_2.1.1      withr_3.0.2       compiler_4.4.2    rstudioapi_0.17.1 tools_4.4.2       clipr_0.8.0       pillar_1.10.1    
[25] evaluate_1.0.3    yaml_2.3.10       rlang_1.1.5       fs_1.6.5         
```

</details>

I've tried a few times and it's always the same file, so I don't think it's likely to be a server error?

**Comment by dramanica** [comment]
Hi @joeroe, it is actually a problem with their server. The file `CHELSA_TraCE21k_tasmin_7_-13_V1.0.tif` is currently missing on their server, and so there is a missing time slice which breaks a the dataset generation code. I have reported it to the paper corresponding author, asking them to upload it.

**Comment by joeroe** [comment]
I see, thanks.

I don't actually need that time slice myself... I can see the internal function download_chelsa_trace21k() has a `time_bp` argument that would allow me to limit which slices to retrieve, but it doesn't appear there's a way to pass that argument via the exported download_dataset() function?

**Comment by dramanica** [comment]
Unfortunately there is currently not a clean way to subset the times; I created some of the infrastructure for it, but not the full interface. If the CHELSA people don't add the file by end of next week, I can have a go at hacking a solution around the missing file.

**Comment by dramanica** [comment]
@joeroe I created a branch `tempfix_chelsatrace` that temporarily fixes the problem by replace timestep -13 with -12 for temperature_min_07. You can install it with `devtools;:install_github()`. Running:
```
download_dataset(dataset= "CHELSA_trace21k_1.0_0.5m_vsi",
                                    bio_var = "temperature_min_07")
```
Now works for me. I haven't had time to check whether there is anything else missing on the CHELSA server, but hopefully there are not other missing files on their server.

**Comment by joeroe** [comment]
Thanks, it now works for `"temperature_min_07"`, but then trips up over `"temperature_max_07"`. I am guessing the problem probably occurs across several variables?

Or actually, based on the number of files listed in their S3 bucket (2652 in `pr/`, 2651 in `tasmin/` and `tasmax/`) it might just be that -13/07 is missing both min and max and that's it.

**Comment by dramanica** [comment]
Good bit of detective work, @joeroe . It does look like ti is inded -13/07 that is missing for both temperatures (sorry, I didn't notice it last time). It should be fixed now on the `tempfix_chelsatrace`.

**Comment by joeroe** [comment]
Looks like that did the trick. `download_dataset("CHELSA_trace21k_1.0_0.5m_vsi", annual = FALSE, monthly = TRUE)` no longer causes an error on that branch. Thanks so much for the help!
